const nomeApp = 'HealthBox';
const baseUrl = 'https://healthbox-api-v1.herokuapp.com/api/';
const keySessao = 'usuariologin';
const baseImagemUrl = 'assets/imagens/';
String senhaGambiarra = '';
const ufs = [
  'AC',
  'AL',
  'AP',
  'AM',
  'BA',
  'CE',
  'DF',
  'ES',
  'GO',
  'MA',
  'MT',
  'MS',
  'MG',
  'PA',
  'PB',
  'PR',
  'PE',
  'PI',
  'RJ',
  'RN',
  'RS',
  'RO',
  'RR',
  'SC',
  'SP',
  'SE',
  'TO'
];
// var especializacoes = Especializacao.listFromJson([
//   {'id': 1, 'nome': 'Acupuntura'},
//   {'id': 2, 'nome': 'Alergia e imunologia'},
//   {'id': 3, 'nome': 'Anestesiologia'},
//   {'id': 4, 'nome': 'Angiologia'},
//   {'id': 5, 'nome': 'Cardiologia'},
//   {'id': 6, 'nome': 'Cirurgia cardiovascular'},
//   {'id': 7, 'nome': 'Cirurgia da mão'},
//   {'id': 8, 'nome': 'Cirurgia de cabeça e pescoço'},
//   {'id': 9, 'nome': 'Cirurgia do aparelho digestivo'},
//   {'id': 10, 'nome': 'Cirurgia geral'},
//   {'id': 11, 'nome': 'Cirurgia oncológica'},
//   {'id': 12, 'nome': 'Cirurgia pediátrica'},
//   {'id': 13, 'nome': 'Cirurgia plástica'},
//   {'id': 14, 'nome': 'Cirurgia torácica'},
//   {'id': 15, 'nome': 'Cirurgia vascular'},
//   {'id': 16, 'nome': 'Clínica médica'},
//   {'id': 17, 'nome': 'Coloproctologia'},
//   {'id': 18, 'nome': 'Dermatologia'},
//   {'id': 19, 'nome': 'Endocrinologia e metabologia'},
//   {'id': 20, 'nome': 'Endoscopia'},
//   {'id': 21, 'nome': 'Gastroenterologia'},
//   {'id': 22, 'nome': 'Genética médica'},
//   {'id': 23, 'nome': 'Geriatria'},
//   {'id': 24, 'nome': 'Ginecologia e obstetrícia'},
//   {'id': 25, 'nome': 'Hematologia e hemoterapia'},
//   {'id': 26, 'nome': 'Homeopatia'},
//   {'id': 27, 'nome': 'Infectologia'},
//   {'id': 28, 'nome': 'Mastologia'},
//   {'id': 29, 'nome': 'Medicina de emergência'},
//   {'id': 30, 'nome': 'Medicina de família e comunidade'},
//   {'id': 31, 'nome': 'Medicina do trabalho'},
//   {'id': 32, 'nome': 'Medicina de tráfego'},
//   {'id': 33, 'nome': 'Medicina esportiva'},
//   {'id': 34, 'nome': 'Medicina física e reabilitação'},
//   {'id': 35, 'nome': 'Medicina intensiva'},
//   {'id': 36, 'nome': 'Medicina legal e perícia médica'},
//   {'id': 37, 'nome': 'Medicina nuclear'},
//   {'id': 38, 'nome': 'Medicina preventiva e social'},
//   {'id': 39, 'nome': 'Nefrologia'},
//   {'id': 40, 'nome': 'Neurocirurgia'},
//   {'id': 41, 'nome': 'Neurologia'},
//   {'id': 42, 'nome': 'Nutrologia'},
//   {'id': 43, 'nome': 'Oftalmologia'},
//   {'id': 44, 'nome': 'Oncologia clínica'},
//   {'id': 45, 'nome': 'Ortopedia e traumatologia'},
//   {'id': 46, 'nome': 'Otorrinolaringologia'},
//   {'id': 47, 'nome': 'Patologia'},
//   {'id': 48, 'nome': 'Patologia clínica/medicina laboratorial'},
//   {'id': 49, 'nome': 'Pediatria'},
//   {'id': 50, 'nome': 'Pneumologia'},
//   {'id': 51, 'nome': 'Psiquiatria'},
//   {'id': 52, 'nome': 'Radiologia e diagnóstico por imagem'},
//   {'id': 53, 'nome': 'Radioterapia'},
//   {'id': 54, 'nome': 'Reumatologia'},
//   {'id': 55, 'nome': 'Urologia'}
// ]);
