import 'package:healthbox/app/data/models/especializacao.dart';

const nomeApp = 'HealthBox';
const baseUrl = 'https://healthbox-api-v1.herokuapp.com/api/';
const keySessao = 'usuariologin';
const baseImagemUrl = 'assets/imagens/';
const ufs = [
  'AC',
  'AL',
  'AP',
  'AM',
  'BA',
  'CE',
  'DF',
  'ES',
  'GO',
  'MA',
  'MT',
  'MS',
  'MG',
  'PA',
  'PB',
  'PR',
  'PE',
  'PI',
  'RJ',
  'RN',
  'RS',
  'RO',
  'RR',
  'SC',
  'SP',
  'SE',
  'TO'
];
var especializacoes = Especializacao.listFromJson([
  {'id': 1, 'titulo': 'Acupuntura'},
  {'id': 2, 'titulo': 'Alergia e imunologia'},
  {'id': 3, 'titulo': 'Anestesiologia'},
  {'id': 4, 'titulo': 'Angiologia'},
  {'id': 5, 'titulo': 'Cardiologia'},
  {'id': 6, 'titulo': 'Cirurgia cardiovascular'},
  {'id': 7, 'titulo': 'Cirurgia da mão'},
  {'id': 8, 'titulo': 'Cirurgia de cabeça e pescoço'},
  {'id': 9, 'titulo': 'Cirurgia do aparelho digestivo'},
  {'id': 10, 'titulo': 'Cirurgia geral'},
  {'id': 11, 'titulo': 'Cirurgia oncológica'},
  {'id': 12, 'titulo': 'Cirurgia pediátrica'},
  {'id': 13, 'titulo': 'Cirurgia plástica'},
  {'id': 14, 'titulo': 'Cirurgia torácica'},
  {'id': 15, 'titulo': 'Cirurgia vascular'},
  {'id': 16, 'titulo': 'Clínica médica'},
  {'id': 17, 'titulo': 'Coloproctologia'},
  {'id': 18, 'titulo': 'Dermatologia'},
  {'id': 19, 'titulo': 'Endocrinologia e metabologia'},
  {'id': 20, 'titulo': 'Endoscopia'},
  {'id': 21, 'titulo': 'Gastroenterologia'},
  {'id': 22, 'titulo': 'Genética médica'},
  {'id': 23, 'titulo': 'Geriatria'},
  {'id': 24, 'titulo': 'Ginecologia e obstetrícia'},
  {'id': 25, 'titulo': 'Hematologia e hemoterapia'},
  {'id': 26, 'titulo': 'Homeopatia'},
  {'id': 27, 'titulo': 'Infectologia'},
  {'id': 28, 'titulo': 'Mastologia'},
  {'id': 29, 'titulo': 'Medicina de emergência'},
  {'id': 30, 'titulo': 'Medicina de família e comunidade'},
  {'id': 31, 'titulo': 'Medicina do trabalho'},
  {'id': 32, 'titulo': 'Medicina de tráfego'},
  {'id': 33, 'titulo': 'Medicina esportiva'},
  {'id': 34, 'titulo': 'Medicina física e reabilitação'},
  {'id': 35, 'titulo': 'Medicina intensiva'},
  {'id': 36, 'titulo': 'Medicina legal e perícia médica'},
  {'id': 37, 'titulo': 'Medicina nuclear'},
  {'id': 38, 'titulo': 'Medicina preventiva e social'},
  {'id': 39, 'titulo': 'Nefrologia'},
  {'id': 40, 'titulo': 'Neurocirurgia'},
  {'id': 41, 'titulo': 'Neurologia'},
  {'id': 42, 'titulo': 'Nutrologia'},
  {'id': 43, 'titulo': 'Oftalmologia'},
  {'id': 44, 'titulo': 'Oncologia clínica'},
  {'id': 45, 'titulo': 'Ortopedia e traumatologia'},
  {'id': 46, 'titulo': 'Otorrinolaringologia'},
  {'id': 47, 'titulo': 'Patologia'},
  {'id': 48, 'titulo': 'Patologia clínica/medicina laboratorial'},
  {'id': 49, 'titulo': 'Pediatria'},
  {'id': 50, 'titulo': 'Pneumologia'},
  {'id': 51, 'titulo': 'Psiquiatria'},
  {'id': 52, 'titulo': 'Radiologia e diagnóstico por imagem'},
  {'id': 53, 'titulo': 'Radioterapia'},
  {'id': 54, 'titulo': 'Reumatologia'},
  {'id': 55, 'titulo': 'Urologia'}
]);
